### ISSUE TITLE
polars_business.cpython-311-x86_64-linux-gnu.so: undefined symbol: _polars_plugin_get_version"

### ISSUE THREAD

**Issue by ciprianmiclaus** [MarcoGorelli/polars-business#28]
Versions:
polars: 0.19.14
polars_business: 0.3.14

The below used to work with:
polars: 0.19.12
polars_business: 0.3.11

Any ideas?

To reproduce:
```python
import datetime
import polars as pl
import polars_business as plb

x = pl.DataFrame([
    {"A": datetime.datetime(2023, 5, 11, 10, 20, 30, 100), "B": 1},
    {"A": datetime.datetime(2023, 6, 10, 11, 21, 31, 101), "B": 2},
    {},
])
x.with_columns(
    C=plb.col("A").bdt.offset_by(
         plb.col("B").map_elements(
                lambda x: f"{x}bd" if x else x, return_dtype=pl.Utf8),
         weekend=("Sat", "Sun"), roll="backward")
)
```

Results in:
```
thread '<unnamed>' panicked at crates/polars-plan/src/dsl/function_expr/plugin.rs:29:18:
called `Result::unwrap()` on an `Err` value: DlSym { desc: "/home/cmiclaus/.local/envs/finrules/lib/python3.11/site-packages/polars_business/polars_business.cpython-311-x86_64-linux-gnu.so: undefined symbol: _polars_plugin_get_version" }
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cmiclaus/.local/envs/finrules/lib/python3.11/site-packages/polars/dataframe/frame.py", line 7967, in with_columns
    return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cmiclaus/.local/envs/finrules/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 3999, in with_columns
    return self._from_pyldf(self._ldf.with_columns(pyexprs))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: DlSym { desc: "/home/cmiclaus/.local/envs/finrules/lib/python3.11/site-packages/polars_business/polars_business.cpython-311-x86_64-linux-gnu.so: undefined symbol: _polars_plugin_get_version" }
```

**Comment by MarcoGorelli** [comment]
thanks @ciprianmiclaus for the report

I don't know, this works for me with `polars==0.19.15` and `polars-business=0.3.15`

Could you show the output of `pl.show_versions()` please?

**Comment by MarcoGorelli** [comment]
Can confirm that I get the same traceback you showed with the versions your reported

If you update the latest versions, it should work fine

There have been some recent changes to the plugin system in Polars, but it should be stable now going forwards
